### ISSUE TITLE
Conflict with plugin that was patched in discord ticket but not in github

### ISSUE THREAD

**Issue by Gyztor** [funkemunky/Kauri#52]
there is a current incompatibility with another plugin called EliteLootBox (https://www.spigotmc.org/resources/elitelootbox-create-your-own-lootbox-custom-item-support-in-game-control-flash-sale.64949/) but was fixed at one point in a discord ticket but never pushed to the github making this error reappear
```
[05:06:23 WARN]: [Kauri] Loaded class co.aikar.locales.MessageKeyProvider from EliteLootbox v2.2.8 which is not a depend or softdepend of this plugin.
[05:06:23 ERROR]: Error occurred while enabling Kauri v2.18.2 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'java.lang.String co.aikar.commands.BukkitLocales.addMessage(java.util.Locale, co.aikar.locales.MessageKeyProvider, java.lang.String)' the class loader 'Kauri-Detections-2.18.2-test3.jar' @453edd58 of the current class, dev/brighten/anticheat/commands/CommandPropertiesManager, and the class loader 'AtlasBukkit-1.11.7-test1.jar' @32dcf6f9 for the method's defining class, co/aikar/commands/Locales, have different Class objects for the type co/aikar/locales/MessageKeyProvider used in the signature (dev.brighten.anticheat.commands.CommandPropertiesManager is in unnamed module of loader 'Kauri-Detections-2.18.2-test3.jar' @453edd58, parent loader java.net.URLClassLoader @5c29bfd; co.aikar.commands.Locales is in unnamed module of loader 'AtlasBukkit-1.11.7-test1.jar' @32dcf6f9, parent loader java.net.URLClassLoader @5c29bfd)
        at dev.brighten.anticheat.commands.CommandPropertiesManager.lambda$new$0(CommandPropertiesManager.java:44) ~[Kauri-Detections-2.18.2-test3.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at java.util.Properties.forEach(Properties.java:1422) ~[?:?]
        at dev.brighten.anticheat.commands.CommandPropertiesManager.<init>(CommandPropertiesManager.java:44) ~[Kauri-Detections-2.18.2-test3.jar:?]
        at dev.brighten.anticheat.Load.load(Load.java:73) ~[Kauri-Detections-2.18.2-test3.jar:?]
        at dev.brighten.anticheat.Kauri.load(Kauri.java:177) ~[Kauri-Detections-2.18.2-test3.jar:?]
        at dev.brighten.anticheat.Kauri.onEnable(Kauri.java:78) ~[Kauri-Detections-2.18.2-test3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[05:06:23 INFO]: [Kauri] Disabling Kauri v2.18.2
```
this also happens on the 2.18.3 version too if you were to build it
there is also this error now, not sure where it came from but i think its just an error with the disabling message:
```
[05:06:23 ERROR]: Error occurred while disabling Kauri v2.18.2 (Is it up to date?)
java.lang.NullPointerException: Cannot read field "storage" because "this.loggerManager" is null
        at dev.brighten.anticheat.Kauri.unload(Kauri.java:126) ~[Kauri-Detections-2.18.2-test3.jar:?]
        at dev.brighten.anticheat.Kauri.onDisable(Kauri.java:82) ~[Kauri-Detections-2.18.2-test3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-379]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-379]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-379]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```
Funkymonkey made a fix for the 2.18.1 at around 05/02/2022 than later on made kauri open source but never pushed the commits that were in the atlas jar and the kauri jar to their respective repositories, from there is been silence other than 2 exchanges and being unable to use kauri at all and not being able to update at all. i will put the jars here that were patched for both atlas and kauri if that helps too but i hope we can get this fixed because i have been unable to use kauri practically at all other than barely getting it to limp along until now when it wont start anymore.
here is both of the jar files from the patched one:
[Kauri-stuff-EliteLootBox-Patched.zip](https://github.com/funkemunky/Kauri/files/8889749/Kauri-stuff-EliteLootBox-Patched.zip)

**Comment by Gyztor** [comment]
newer errors:
```
[13:09:38 WARN]: [Kauri] Loaded class co.aikar.locales.MessageKeyProvider from EliteLootbox v2.2.8 which is not a depend or softdepend of this plugin.
[13:09:38 ERROR]: Error occurred while enabling Kauri v2.18.3 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'java.lang.String co.aikar.commands.BukkitLocales.addMessage(java.util.Locale, co.aikar.locales.MessageKeyProvider, java.lang.String)' the class loader 'Kauri-Detections-2.18.3.jar' @2b14b576 of the current class, dev/brighten/anticheat/commands/CommandPropertiesManager, and the class loader 'AtlasBukkit-1.11.7-test3.jar' @4c098425 for the method's defining class, co/aikar/commands/Locales, have different Class objects for the type co/aikar/locales/MessageKeyProvider used in the signature (dev.brighten.anticheat.commands.CommandPropertiesManager is in unnamed module of loader 'Kauri-Detections-2.18.3.jar' @2b14b576, parent loader java.net.URLClassLoader @5c29bfd; co.aikar.commands.Locales is in unnamed module of loader 'AtlasBukkit-1.11.7-test3.jar' @4c098425, parent loader java.net.URLClassLoader @5c29bfd)
        at dev.brighten.anticheat.commands.CommandPropertiesManager.lambda$new$0(CommandPropertiesManager.java:44) ~[Kauri-Detections-2.18.3.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at java.util.Properties.forEach(Properties.java:1422) ~[?:?]
        at dev.brighten.anticheat.commands.CommandPropertiesManager.<init>(CommandPropertiesManager.java:44) ~[Kauri-Detections-2.18.3.jar:?]
        at dev.brighten.anticheat.Load.load(Load.java:73) ~[Kauri-Detections-2.18.3.jar:?]
        at dev.brighten.anticheat.Kauri.load(Kauri.java:177) ~[Kauri-Detections-2.18.3.jar:?]
        at dev.brighten.anticheat.Kauri.onEnable(Kauri.java:78) ~[Kauri-Detections-2.18.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[13:09:38 INFO]: [Kauri] Disabling Kauri v2.18.3
```
error 2:
```
[13:09:38 ERROR]: Error occurred while disabling Kauri v2.18.3 (Is it up to date?)
java.lang.NullPointerException: Cannot read field "storage" because "this.loggerManager" is null
        at dev.brighten.anticheat.Kauri.unload(Kauri.java:126) ~[Kauri-Detections-2.18.3.jar:?]
        at dev.brighten.anticheat.Kauri.onDisable(Kauri.java:82) ~[Kauri-Detections-2.18.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-386]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-386]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-386]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by Gyztor** [comment]
Still persists in latest

**Comment by funkemunky** [comment]
Try these versions, I think this should fix it:

Kauri Alpha: https://github.com/funkemunky/Kauri/suites/7787768326/artifacts/328064677
Atlas Alpha: https://github.com/funkemunky/Atlas/suites/7787733915/artifacts/328064771

**Comment by Gyztor** [comment]
error still persists
```
[15:31:35 WARN]: [Kauri] Loaded class co.aikar.locales.MessageKeyProvider from EliteLootbox v2.3.1 which is not a depend or softdepend of this plugin.
[15:31:35 ERROR]: Error occurred while enabling Kauri v2.19 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'java.lang.String cc.funkemunky.api.co.aikar.commands.BukkitLocales.addMessage(java.util.Locale, co.aikar.locales.MessageKeyProvider, java.lang.String)' the class loader 'Kauri-Detections-2.19-test1.jar' @31efa60b of the current class, dev/brighten/anticheat/commands/CommandPropertiesManager, and the class loader 'AtlasBukkit-1.12.1-test1.jar' @7fd0a371 for the method's defining class, cc/funkemunky/api/co/aikar/commands/Locales, have different Class objects for the type co/aikar/locales/MessageKeyProvider used in the signature (dev.brighten.anticheat.commands.CommandPropertiesManager is in unnamed module of loader 'Kauri-Detections-2.19-test1.jar' @31efa60b, parent loader java.net.URLClassLoader @5c29bfd; cc.funkemunky.api.co.aikar.commands.Locales is in unnamed module of loader 'AtlasBukkit-1.12.1-test1.jar' @7fd0a371, parent loader java.net.URLClassLoader @5c29bfd)
        at dev.brighten.anticheat.commands.CommandPropertiesManager.lambda$new$0(CommandPropertiesManager.java:44) ~[Kauri-Detections-2.19-test1.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at java.util.Properties.forEach(Properties.java:1422) ~[?:?]
        at dev.brighten.anticheat.commands.CommandPropertiesManager.<init>(CommandPropertiesManager.java:44) ~[Kauri-Detections-2.19-test1.jar:?]
        at dev.brighten.anticheat.Load.load(Load.java:72) ~[Kauri-Detections-2.19-test1.jar:?]
        at dev.brighten.anticheat.Kauri.load(Kauri.java:177) ~[Kauri-Detections-2.19-test1.jar:?]
        at dev.brighten.anticheat.Kauri.onEnable(Kauri.java:78) ~[Kauri-Detections-2.19-test1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[15:31:35 INFO]: [Kauri] Disabling Kauri v2.19
[15:31:35 INFO]: Kauri has been shutdown. Removing its hooks and listeners...
[15:31:35 INFO]: Completed!
[15:31:35 INFO]: Unloading DataManager...
[15:31:35 INFO]: Unregistering Kauri API...
[15:31:35 INFO]: Unregistering processors...
[15:31:35 INFO]: Unregistering logging and database...
[15:31:35 INFO]: Unregistering Bukkit listeners...
[15:31:35 INFO]: Unregistering commands...
[15:31:35 INFO]: Shutting down all Bukkit tasks...
[15:31:35 INFO]: Unloading Discord Webhooks...
[15:31:35 INFO]: Unloading Discord Webhook...
[15:31:35 INFO]: Completed!
[15:31:35 INFO]: Stopping log process...
[15:31:35 ERROR]: Error occurred while disabling Kauri v2.19 (Is it up to date?)
java.lang.NullPointerException: Cannot read field "storage" because "this.loggerManager" is null
        at dev.brighten.anticheat.Kauri.unload(Kauri.java:126) ~[Kauri-Detections-2.19-test1.jar:?]
        at dev.brighten.anticheat.Kauri.onDisable(Kauri.java:82) ~[Kauri-Detections-2.19-test1.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
```

**Comment by Gyztor** [comment]
this error also needs to be addressed too https://github.com/funkemunky/Atlas/issues/46
other wise i cant even join the server atlas is on. makes everything that relies on atlas completely unusable.

**Comment by Gyztor** [comment]
still exists as of commit 2a27ea34dbba3fa087a656a2f4ba313e9d1cd782
```
[06:12:56 WARN]: [Kauri] Loaded class co.aikar.locales.MessageKeyProvider from EliteLootbox v2.3.1 which is not a depend or softdepend of this plugin.
[06:12:56 ERROR]: Error occurred while enabling Kauri v2.19 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'java.lang.String cc.funkemunky.api.co.aikar.commands.BukkitLocales.addMessage(java.util.Locale, co.aikar.locales.MessageKeyProvider, java.lang.String)' the class loader 'Kauri-Detections-2.19-test3.jar' @2327cc18 of the current class, dev/brighten/anticheat/commands/CommandPropertiesManager, and the class loader 'AtlasBukkit-1.12.1-test4.jar' @2b46d48d for the method's defining class, cc/funkemunky/api/co/aikar/commands/Locales, have different Class objects for the type co/aikar/locales/MessageKeyProvider used in the signature (dev.brighten.anticheat.commands.CommandPropertiesManager is in unnamed module of loader 'Kauri-Detections-2.19-test3.jar' @2327cc18, parent loader java.net.URLClassLoader @5c29bfd; cc.funkemunky.api.co.aikar.commands.Locales is in unnamed module of loader 'AtlasBukkit-1.12.1-test4.jar' @2b46d48d, parent loader java.net.URLClassLoader @5c29bfd)
        at dev.brighten.anticheat.commands.CommandPropertiesManager.lambda$new$0(CommandPropertiesManager.java:44) ~[Kauri-Detections-2.19-test3.jar:?]
        at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1603) ~[?:?]
        at java.util.Properties.forEach(Properties.java:1422) ~[?:?]
        at dev.brighten.anticheat.commands.CommandPropertiesManager.<init>(CommandPropertiesManager.java:44) ~[Kauri-Detections-2.19-test3.jar:?]
        at dev.brighten.anticheat.Load.load(Load.java:72) ~[Kauri-Detections-2.19-test3.jar:?]
        at dev.brighten.anticheat.Kauri.load(Kauri.java:177) ~[Kauri-Detections-2.19-test3.jar:?]
        at dev.brighten.anticheat.Kauri.onEnable(Kauri.java:78) ~[Kauri-Detections-2.19-test3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[06:12:56 INFO]: [Kauri] Disabling Kauri v2.19
[06:12:56 INFO]: Kauri has been shutdown. Removing its hooks and listeners...
[06:12:56 INFO]: Completed!
[06:12:56 INFO]: Unloading DataManager...
[06:12:56 INFO]: Unregistering Kauri API...
[06:12:56 INFO]: Unregistering processors...
[06:12:56 INFO]: Unregistering logging and database...
[06:12:56 INFO]: Unregistering Bukkit listeners...
[06:12:56 INFO]: Unregistering commands...
[06:12:56 INFO]: Shutting down all Bukkit tasks...
[06:12:56 INFO]: Unloading Discord Webhooks...
[06:12:56 INFO]: Unloading Discord Webhook...
[06:12:56 INFO]: Completed!
[06:12:56 INFO]: Stopping log process...
[06:12:56 ERROR]: Error occurred while disabling Kauri v2.19 (Is it up to date?)
java.lang.NullPointerException: Cannot read field "storage" because "this.loggerManager" is null
        at dev.brighten.anticheat.Kauri.unload(Kauri.java:126) ~[Kauri-Detections-2.19-test3.jar:?]
        at dev.brighten.anticheat.Kauri.onDisable(Kauri.java:82) ~[Kauri-Detections-2.19-test3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:578) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[paper-1.18.2.jar:git-Paper-387]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:665) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:432) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1164) ~[paper-1.18.2.jar:git-Paper-387]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.18.2.jar:git-Paper-387]
```
but error with atlas#46 seems to be fixed so testing this conflict will be doable.
